import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { DesktopHeader } from "@/components/header/desktop";
import { Footer } from "@/components/footer";
import { Suspense } from "react";
import { MobileHeader } from "@/components/header/mobile";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { useBackend } from "@/hooks/use-backend";
import { useFilter } from "@/hooks/use-filter";

export const metadata: Metadata = {
  title: "Fazendo Arte com Agulhas",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { handleUserLogin } = useBackend();
  const { getUser, isAuthenticated } = getKindeServerSession();
  const isLogedIn = await isAuthenticated();
  const user = await getUser();

  if(isLogedIn && user) {
    if(!user?.email || !user?.id || !user?.given_name) return;
    handleUserLogin({id: user.id, email: user.email, name: user.given_name});
  }

  return (
    <html lang="pt-br" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo-img.ico" type="image/x-icon" />
      </head>
      <body className="flex flex-col justify-between">
        <Providers>
          <Suspense fallback={<div>Layout header suspense</div>}>
            <DesktopHeader />
            <MobileHeader />
          </Suspense>
            {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
