import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { DesktopHeader } from "@/components/header/desktop";
import { Footer } from "@/components/footer";
import { Suspense } from "react";
import { MobileHeader } from "@/components/header/mobile";

export const metadata: Metadata = {
  title: "Fazendo Arte com Agulhas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo-img.ico" type="image/x-icon" />
      </head>
      <body className="flex flex-col justify-between">
        <Providers>
          <Suspense fallback={<div>Layout header suspense</div>}>
            <DesktopHeader />
            <MobileHeader />
          </Suspense>
            {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
